# Generated by Django 4.2.10 on 2024-03-25 09:58

from django.db import migrations, models
import reservation.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(validators=[reservation.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[reservation.validators.validate_phone_number]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'time_slot', 'location')},
        ),
    ]
